"use strict";
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
Object.defineProperty(exports, "__esModule", { value: true });
exports.convertMarkdownToTeamsHTML = convertMarkdownToTeamsHTML;
exports.microsoftTeamsChannelPostMessage = microsoftTeamsChannelPostMessage;
exports.createMicrosoftTeamsChannelClient = createMicrosoftTeamsChannelClient;
const filetype_js_1 = require("./filetype.js");
const cleaners_js_1 = require("./cleaners.js");
const fetch_js_1 = require("./fetch.js");
const host_js_1 = require("./host.js");
const htmlescape_js_1 = require("./htmlescape.js");
const util_js_1 = require("./util.js");
const indent_js_1 = require("./indent.js");
const constants_js_1 = require("./constants.js");
const unwrappers_js_1 = require("./unwrappers.js");
const filebytes_js_1 = require("./filebytes.js");
const node_path_1 = require("node:path");
const frontmatter_js_1 = require("./frontmatter.js");
/**
 * Converts a Markdown string into HTML formatted for Microsoft Teams.
 *
 * @param markdown - The Markdown content to be converted.
 * Supports headers, lists, links, bold, italic, underlined, code, strikethrough, and blockquotes.
 *
 * @returns An object containing:
 * - `content`: The converted HTML string suitable for Microsoft Teams.
 * - `subject`: The extracted title if available, or undefined.
 */
function convertMarkdownToTeamsHTML(markdown) {
    // using regexes, convert headers, lists, links, bold, italic, code, and quotes
    const { content, frontmatter } = (0, frontmatter_js_1.splitMarkdown)(markdown || "");
    const fm = (0, frontmatter_js_1.frontmatterTryParse)(frontmatter);
    let subject = fm?.value?.title;
    const html = "<div>" +
        (content || "")
            .replace(/^# (.*$)/gim, (m, t) => {
            subject = t;
            return "";
        })
            .replace(/^#### (.*$)/gim, "<h3>$1</h3>")
            .replace(/^### (.*$)/gim, "<h2>$1</h2>")
            .replace(/^## (.*$)/gim, "<h1>$1</h1>")
            .replace(/^> (.*$)/gim, "<blockquote>$1</blockquote>\n")
            .replace(/\*\*(.*)\*\*/gim, "<b>$1</b>")
            .replace(/\*(.*)\*/gim, "<i>$1</i>")
            .replace(/__(.*)__/gim, "<u>$1</u>")
            .replace(/`(.*?)`/gim, "<code>$1</code>")
            .replace(/~~(.*?)~~/gim, "<strike>$1</strike>")
            .replace(/^- (.*$)/gim, "<br/>- $1") +
        "</div>";
    return { content: html.trim(), subject: subject?.trim() };
}
function parseTeamsChannelUrl(url) {
    const m = /^https:\/\/teams.microsoft.com\/[^/]{1,32}\/channel\/(?<channelId>.+)\/.*\?groupId=(?<teamId>([a-z0-9-])+)$/.exec(url);
    if (!m)
        throw new Error("Invalid Teams channel URL");
    const { teamId, channelId } = m.groups;
    return { teamId, channelId };
}
function generatedByFooter(script, info) {
    if (!script)
        return `\n<blockquote>AI-generated may be incorrect</blockquote>\n`;
    return `\n<blockquote>AI-generated by ${info?.runUrl ? `<a href="${(0, htmlescape_js_1.HTMLEscape)(info.runUrl)}">${(0, htmlescape_js_1.HTMLEscape)(script.id)}</a>` : (0, htmlescape_js_1.HTMLEscape)(script.id)} may be incorrect</blockquote>\n`;
}
/**
 * Uploads a file to the files storage of a Microsoft Teams channel.
 * @param channelUrl Shared channel link in the format https://teams.microsoft.com/l/channel/<channelId>/<channelName>?groupId=<teamId>
 * @param filename
 * @returns
 */
async function microsoftTeamsChannelUploadFile(token, channelUrl, file, options) {
    const { disclaimer } = options || {};
    const filename = (0, unwrappers_js_1.filenameOrFileToFilename)(file);
    const description = typeof file === "object" ? file.description : undefined;
    (0, util_js_1.logVerbose)(`teams: uploading ${filename}...`);
    const { teamId, channelId } = parseTeamsChannelUrl(channelUrl);
    const Authorization = `Bearer ${token}`;
    const channelInfoUrl = `https://graph.microsoft.com/v1.0/teams/${teamId}/channels/${channelId}`;
    const fetch = await (0, fetch_js_1.createFetch)({ ...(options || {}), retries: 1 });
    const channelInfoRes = await fetch(channelInfoUrl, {
        headers: {
            Authorization,
        },
    });
    if (!channelInfoRes.ok) {
        throw new Error(`Failed to get channel info: ${channelInfoRes.status} ${channelInfoRes.statusText}`);
    }
    const channelInfo = await channelInfoRes.json();
    const root = channelInfo.displayName;
    // resolve channel folder name
    const content = await (0, filebytes_js_1.resolveFileBytes)(file, options);
    if (!file)
        throw new Error(`${filename} not found`);
    const folder = options?.folder || constants_js_1.TOOL_ID;
    const itemUrl = `https://graph.microsoft.com/v1.0/groups/${teamId}/drive/root:/${root}/${folder}/${(0, node_path_1.basename)(filename)}`;
    const contentUrl = `${itemUrl}:/content`;
    const mime = await (0, filetype_js_1.fileTypeFromBuffer)(content);
    const res = await fetch(contentUrl, {
        method: "PUT",
        headers: {
            Authorization,
            "Content-Type": mime?.mime || "application/octet-stream",
        },
        body: content,
    });
    if (!res.ok) {
        (0, util_js_1.logError)(await res.text());
        throw new Error(`Failed to upload file: ${res.status} ${res.statusText}`);
    }
    const j = (await res.json());
    (0, util_js_1.logVerbose)(`teams: uploaded ${filename} to ${j.webUrl}`);
    if (disclaimer || description) {
        const html = convertMarkdownToTeamsHTML(description);
        if (disclaimer)
            html.content += disclaimer;
        const dbody = (0, cleaners_js_1.deleteUndefinedValues)({
            description: html.content,
            title: html.subject,
        });
        const resd = await fetch(itemUrl, {
            method: "PATCH",
            headers: {
                Authorization,
                "Content-Type": "application/json",
            },
            body: JSON.stringify(dbody),
        });
        if (!resd.ok) {
            (0, util_js_1.logVerbose)(`description: ${dbody.description}`);
            (0, util_js_1.logVerbose)(await resd.json());
            throw new Error(`Failed to update file description: ${resd.status} ${resd.statusText}`);
        }
    }
    return j;
}
/**
 * Sends a message to a Microsoft Teams channel, optionally including file attachments.
 *
 * @param channelUrl The URL of the Microsoft Teams channel, in the format https://teams.microsoft.com/l/channel/<channelId>/<channelName>?groupId=<teamId>.
 * @param message The message content to post in Markdown format. It will be converted to HTML.
 * @param options Additional configurations for the message.
 *   - script: The script context to include an attribution footer.
 *   - info: Metadata about the originating script or run (e.g., runUrl).
 *   - files: A list of files to attach to the message. Files are uploaded to the channel's storage.
 *   - folder: The folder in the channel's storage where files will be uploaded, if applicable.
 *   - disclaimer: A disclaimer to append to the message. If a string, it is used directly. Pass false to omit it.
 * @returns A promise resolving to the created message entity containing the message's metadata, including its web URL.
 */
async function microsoftTeamsChannelPostMessage(channelUrl, message, options) {
    (0, util_js_1.logVerbose)(`teams: posting message to ${channelUrl}`);
    const { files = [] } = options || {};
    const { teamId, channelId } = parseTeamsChannelUrl(channelUrl);
    const runtimeHost = (0, host_js_1.resolveRuntimeHost)();
    const authToken = await runtimeHost.microsoftGraphToken.token("default");
    const token = authToken?.token?.token;
    if (!token) {
        (0, util_js_1.logError)("Microsoft Graph token not available");
        return undefined;
    }
    // convert message to html
    const { content, subject } = convertMarkdownToTeamsHTML(message);
    const disclaimer = typeof options.disclaimer === "string"
        ? `\n<blockquote>${(0, htmlescape_js_1.HTMLEscape)(options.disclaimer)}</blockquote>\n`
        : options.disclaimer !== false
            ? generatedByFooter(options?.script, options?.info)
            : undefined;
    const body = (0, cleaners_js_1.deleteUndefinedValues)({
        body: {
            contentType: "html",
            content,
        },
        subject,
        attachments: [],
    });
    for (const file of files) {
        const fres = await microsoftTeamsChannelUploadFile(token, channelUrl, file, {
            ...options,
            disclaimer,
        });
        const guid = crypto.randomUUID();
        body.body.content += "\n" + `<attachment id="${guid}"></attachment>`;
        body.attachments.push({
            id: guid,
            contentType: "reference",
            contentUrl: fres.webUrl,
            name: fres.name,
            thumbnailUrl: null,
        });
    }
    // finalize message
    if (disclaimer)
        body.body.content += disclaimer;
    const url = `https://graph.microsoft.com/v1.0/teams/${teamId}/channels/${channelId}/messages`;
    const fetch = await (0, fetch_js_1.createFetch)({ ...(options || {}), retries: 1 });
    const response = await fetch(url, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
    });
    if (!response.ok) {
        const err = await response.text();
        (0, util_js_1.logError)(err);
        return undefined;
    }
    const data = await response.json();
    const { webUrl } = data;
    (0, util_js_1.logVerbose)(`teams: message created at ${webUrl}`);
    return data;
}
class MicrosoftTeamsChannelClient {
    channelUrl;
    constructor(channelUrl) {
        this.channelUrl = channelUrl;
    }
    get teamId() {
        const { teamId } = parseTeamsChannelUrl(this.channelUrl);
        return teamId;
    }
    get channelId() {
        const { channelId } = parseTeamsChannelUrl(this.channelUrl);
        return channelId;
    }
    /**
     * Posts a message with attachments to the channel
     * @param message
     * @param options
     */
    async postMessage(message, options) {
        const { files, disclaimer } = options || {};
        const res = await microsoftTeamsChannelPostMessage(this.channelUrl, (0, indent_js_1.dedent)(message), {
            files,
            disclaimer,
        });
        return res.webUrl;
    }
    toString() {
        return this.channelUrl;
    }
}
/**
 * Creates a Microsoft Teams Channel Client for interacting with a Teams channel.
 * This client allows posting messages and managing attachments in the specified channel.
 *
 * @param url The URL of the Microsoft Teams channel. Must be in the format:
 *            `https://teams.microsoft.com/.../channel/<channelId>/<channelName>?groupId=<teamId>`.
 *            If not provided, the function attempts to retrieve the URL from the
 *            GENAISCRIPT_TEAMS_CHANNEL_URL or GENAISCRIPT_TEAMS_URL environment variables.
 *
 * @throws Error if the provided URL is invalid or cannot be parsed.
 *
 * @returns An instance of a MicrosoftTeamsChannelClient for interacting with the specified channel.
 */
function createMicrosoftTeamsChannelClient(url) {
    if (!url)
        url = process.env.GENAISCRIPT_TEAMS_CHANNEL_URL || process.env.GENAISCRIPT_TEAMS_URL;
    if (!parseTeamsChannelUrl(url))
        throw new Error("Invalid Teams channel URL");
    return new MicrosoftTeamsChannelClient(url);
}
//# sourceMappingURL=teams.js.map