def(
    "ProjectGoal",
    await retreival.query("What is the goal of the project, and how is it described in plain language?", {
        files: pdfs,
    })
)

def(
    "MicrosoftRelation",
    await retreival.query("How does this project relate to any Microsoft systems or products?", {
        files: pdfs,
    })
)

def(
    "SharedAssets",
    await retreival.query("What assets are you planning to share (e.g., demo, source code, models, data)?", {
        files: pdfs,
    })
)

def(
    "AssetRecipients",
    await retreival.query("Who are the intended recipients of the shared assets (e.g., Open Source/Public, partners, product teams)?", {
        files: pdfs,
    })
)

def(
    "SharingGoals",
    await retreival.query("What are the goals for sharing these assets?", {
        files: pdfs,
    })
)

def(
    "DataImpact",
    await retreival.query("What are the top impacts that the makeup of your data could have on your work?", {
        files: pdfs,
    })
)

def(
    "SystemLimitations",
    await retreival.query("What are the current limitations of the system, including scenarios where it may not perform well?", {
        files: pdfs,
    })
)

def(
    "MaliciousUse",
    await retreival.query("If a malicious entity were to use the assets you share, what could happen? What are the most obvious abuse scenarios?", {
        files: pdfs,
    })
)

def(
    "UnintendedMisuse",
    await retreival.query("Is it possible for your assets to be misused unintentionally? If so, how?", {
        files: pdfs,
    })
)

def(
    "RiskMitigations",
    await retreival.query("What mitigations do you intend to use for risks identified?", {
        files: pdfs,
    })
)

def(
    "RealWorldUses",
    await retreival.query("What are the most likely real-world uses of the research project?", {
        files: pdfs,
    })
)

def(
    "RealWorldMisuses",
    await retreival.query("What are the most likely real-world misuses of the research project?", {
        files: pdfs,
    })
)

def(
    "StakeholderImpact",
    await retreival.query("Who are the possible stakeholders that would be most impacted by both your research and the future real-world uses?", {
        files: pdfs,
    })
)

def(
    "IntendedUseCases",
    await retreival.query("What are the intended use cases for this work?", {
        files: pdfs,
    })
)

def(
    "BestSuitedUseCases",
    await retreival.query("Which use cases and stakeholders is this work best suited for, and why?", {
        files: pdfs,
    })
)

def(
    "AnticipatedHarms",
    await retreival.query("After reflecting on your real-world use cases, stakeholders, and data, what are the anticipated harms to stakeholders and how can the identified harms be mitigated?", {
        files: pdfs,
    })
)

def(
    "DiversityImpact",
    await retreival.query("How will the project impact the diversity and inclusivity of AI technology?", {
        files: pdfs,
    })
)

def(
    "PrivacySecurity",
    await retreival.query("What measures are in place to ensure the privacy and security of data used or generated by the project?", {
        files: pdfs,
    })
)

def(
    "EthicalMonitoring",
    await retreival.query("How will the project's outcomes be monitored for long-term ethical implications and societal impact?", {
        files: pdfs,
    })
)

def(
    "StakeholderFeedback",
    await retreival.query("What processes are in place for stakeholders to provide feedback or raise concerns about the project's impact?", {
        files: pdfs,
    })
)

def(
    "ResponsibleAIPrinciples",
    await retreival.query("How does the project align with Microsoft's overall Responsible AI principles and strategies?", {
        files: pdfs,
    })
)

def(
    "EnvironmentalImpact",
    await retreival.query("Are there any environmental impacts associated with the deployment or operation of the project's technology?", {
        files: pdfs,
    })
)

def(
    "PublicTrust",
    await retreival.query("How will the project contribute to or detract from the public's trust in AI?", {
        files: pdfs,
    })
)

def(
    "WorkforceImpact",
    await retreival.query("What are the potential impacts on employment and the workforce due to the project's technology?", {
        files: pdfs,
    })
)

def(
    "BiasAddressal",
    await retreival.query("How will the project address potential biases in AI algorithms and decision-making processes?", {
        files: pdfs,
    })
)

def(
    "ImpactReview",
    await retreival.query("What is the plan for ongoing review and revision of the impact assessment as the project evolves?", {
        files: pdfs,
    })
)

const queries = [
    "ProjectGoal",
    "MicrosoftRelation",
    "SharedAssets",
    "AssetRecipients",
    "SharingGoals",
    "DataImpact",
    "SystemLimitations",
    "MaliciousUse",
    "UnintendedMisuse",
    "RiskMitigations",
    "RealWorldUses",
    "RealWorldMisuses",
    "StakeholderImpact",
    "IntendedUseCases",
    "BestSuitedUseCases",
    "AnticipatedHarms",
    "DiversityImpact",
    "PrivacySecurity",
    "EthicalMonitoring",
    "StakeholderFeedback",
    "ResponsibleAIPrinciples",
    "EnvironmentalImpact",
    "PublicTrust",
    "WorkforceImpact",
    "BiasAddressal",
    "ImpactReview"
];
