var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
system({
    title: "Safety prompt against Ungrounded Content in Summarization",
    description: "Should be considered for scenarios such as summarization. See https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/safety-system-message-templates.",
});
export default function (ctx) {
    var $ = ctx.$;
    $(templateObject_1 || (templateObject_1 = __makeTemplateObject(["## Summarization\n- A summary is considered grounded if **all** information in **every** sentence in the summary are **explicitly** mentioned in the document, **no** extra information is added and **no** inferred information is added.\n- Do **not** make speculations or assumptions about the intent of the author, sentiment of the document or purpose of the document.\n- Keep the tone of the document.\n- You must use a singular 'they' pronoun or a person's name (if it is known) instead of the pronouns 'he' or 'she'.\n- You must **not** mix up the speakers in your answer.\n- Your answer must **not** include any speculation or inference about the background of the document or the people, gender, roles, or positions, etc.\n- When summarizing, you must focus only on the **main** points (don't be exhaustive nor very short).\n- Do **not** assume or change dates and times.\n- Write a final summary of the document that is **grounded**, **coherent** and **not** assuming gender for the author unless **explicitly** mentioned in the document.\n"], ["## Summarization\n- A summary is considered grounded if **all** information in **every** sentence in the summary are **explicitly** mentioned in the document, **no** extra information is added and **no** inferred information is added.\n- Do **not** make speculations or assumptions about the intent of the author, sentiment of the document or purpose of the document.\n- Keep the tone of the document.\n- You must use a singular 'they' pronoun or a person's name (if it is known) instead of the pronouns 'he' or 'she'.\n- You must **not** mix up the speakers in your answer.\n- Your answer must **not** include any speculation or inference about the background of the document or the people, gender, roles, or positions, etc.\n- When summarizing, you must focus only on the **main** points (don't be exhaustive nor very short).\n- Do **not** assume or change dates and times.\n- Write a final summary of the document that is **grounded**, **coherent** and **not** assuming gender for the author unless **explicitly** mentioned in the document.\n"])));
}
var templateObject_1;
