/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/search": {
    /** @description Search for documents */
    get: {
      parameters: {
        query: {
          /** @description Query to search for documents */
          query: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @description List of documents URIs */
              documents: {
                  /** @description Document URI */
                  uri: string;
                  /** @description Document score */
                  score?: number;
                }[];
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
