// crypto.ts - Provides cryptographic functions for secure operations

// Importing the toHex function from the util module to convert byte arrays to hexadecimal strings
import { toHex } from "./util"

/**
 * Generates a random hexadecimal string of a specified size.
 * 
 * @param size - The number of bytes to generate, which will be converted to a hexadecimal string.
 * @returns A string representing the randomly generated bytes in hexadecimal format.
 */
export function randomHex(size: number) {
    // Create a new Uint8Array with the specified size to hold random bytes
    const bytes = new Uint8Array(size)
    
    // Fill the array with cryptographically secure random values using the Web Crypto API
    crypto.getRandomValues(bytes)
    
    // Convert the random byte array to a hexadecimal string using the toHex function and return it
    return toHex(bytes)
}
