import { assert, log } from "node:console"
import { GITHUB_API_VERSION, GITHUB_TOKEN } from "./constants"
import { GenerationResult } from "./expander"
import { createFetch } from "./fetch"
import { host } from "./host"
import { link, prettifyMarkdown } from "./markdown"
import { logError, logVerbose, normalizeInt } from "./util"
import { YAMLStringify } from "./yaml"

export interface GithubConnectionInfo {
    token: string
    apiUrl?: string
    repository: string
    owner: string
    repo: string
    ref?: string
    sha?: string
    issue?: number
    runId?: string
    runUrl?: string
}

export function parseGHTokenFromEnv(
    env: Record<string, string>
): GithubConnectionInfo {
    const token = env.GITHUB_TOKEN
    const apiUrl = env.GITHUB_API_URL || "https://api.github.com"
    const repository = env.GITHUB_REPOSITORY
    const [owner, repo] = repository?.split("/", 2) || [undefined, undefined]
    const ref = env.GITHUB_REF
    const sha = env.GITHUB_SHA
    const runId = env.GITHUB_RUN_ID
    const serverUrl = env.GITHUB_SERVER_URL
    const runUrl =
        serverUrl && runId
            ? `${serverUrl}/${repository}/actions/runs/${runId}`
            : undefined
    const issue = normalizeInt(
        /^refs\/pull\/(?<issue>\d+)\/merge$/.exec(ref || "")?.groups?.issue
    )

    return {
        token,
        apiUrl,
        repository,
        owner,
        repo,
        ref,
        sha,
        issue,
        runId,
        runUrl,
    }
}

// https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#update-a-pull-request
export async function githubUpsetPullRequest(
    script: PromptScript,
    info: GithubConnectionInfo,
    text: string,
    commentTag: string
) {
    const { apiUrl, repository, issue } = info

    if (!issue) return { updated: false, statusText: "missing issue number" }
    const token = await host.readSecret(GITHUB_TOKEN)
    if (!token) return { updated: false, statusText: "missing github token" }

    text = appendGeneratedComment(script, info, text)

    const fetch = await createFetch()
    const url = `${apiUrl}/repos/${repository}/pulls/${issue}`
    // get current body
    const resGet = await fetch(url, {
        method: "GET",
        headers: {
            Accept: "application/vnd.github+json",
            Authorization: `Bearer ${token}`,
            "X-GitHub-Api-Version": GITHUB_API_VERSION,
        },
    })
    const resGetJson = (await resGet.json()) as { body: string }
    let { body } = resGetJson
    if (!body) body = ""
    const tag = `\n\n<!-- genaiscript begin ${commentTag} -->\n\n`
    const endTag = `\n\n<!-- genaiscript end ${commentTag} -->\n\n`

    const start = body.indexOf(tag)
    const end = body.indexOf(endTag)
    if (start > -1 && end > -1 && start < end) {
        body = body.slice(0, start + tag.length) + text + body.slice(end)
    } else {
        body = body + tag + text + endTag
    }

    const res = await fetch(url, {
        method: "PATCH",
        headers: {
            Accept: "application/vnd.github+json",
            Authorization: `Bearer ${token}`,
            "X-GitHub-Api-Version": GITHUB_API_VERSION,
        },
        body: JSON.stringify({ body }),
    })
    const r = {
        updated: res.status === 200,
        statusText: res.statusText,
    }

    if (!r.updated)
        logError(
            `pull request ${info.repository}/pull/${info.issue} update failed, ${r.statusText}`
        )
    else
        logVerbose(`pull request ${info.repository}/pull/${info.issue} updated`)

    return r
}

function appendGeneratedComment(
    script: PromptScript,
    info: GithubConnectionInfo,
    text: string
) {
    return prettifyMarkdown(
        `${text}\n\n> generated by genaiscript ${link(script.id, info.runUrl)}\n\n`
    )
}

// https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
export async function githubCreateIssueComment(
    script: PromptScript,
    info: GithubConnectionInfo,
    body: string,
    commentTag: string
): Promise<{ created: boolean; statusText: string; html_url?: string }> {
    const { apiUrl, repository, issue } = info

    if (!issue) return { created: false, statusText: "missing issue number" }
    const token = await host.readSecret(GITHUB_TOKEN)
    if (!token) return { created: false, statusText: "missing github token" }

    const fetch = await createFetch()
    const url = `${apiUrl}/repos/${repository}/issues/${issue}/comments`

    body = appendGeneratedComment(script, info, body)

    if (commentTag) {
        const tag = `<!-- genaiscript ${commentTag} -->`
        body = `${body}\n\n${tag}\n\n`
        // try to find the existing comment
        const resListComments = await fetch(`${url}?per_page=100`, {
            headers: {
                Accept: "application/vnd.github+json",
                Authorization: `Bearer ${token}`,
                "X-GitHub-Api-Version": GITHUB_API_VERSION,
            },
        })
        if (resListComments.status !== 200)
            return { created: false, statusText: resListComments.statusText }
        const comments = (await resListComments.json()) as {
            id: string
            body: string
        }[]

        const comment = comments.find((c) => c.body.includes(tag))
        if (comment) {
            const delurl = `${apiUrl}/repos/${repository}/issues/comments/${comment.id}`
            const resd = await fetch(delurl, {
                method: "DELETE",
                headers: {
                    Authorization: `Bearer ${token}`,
                    "X-GitHub-Api-Version": GITHUB_API_VERSION,
                },
            })
            if (!resd.ok)
                logError(`issue comment delete failed, ` + resd.statusText)
        }
    }

    const res = await fetch(url, {
        method: "POST",
        headers: {
            Accept: "application/vnd.github+json",
            Authorization: `Bearer ${token}`,
            "X-GitHub-Api-Version": GITHUB_API_VERSION,
        },
        body: JSON.stringify({ body }),
    })
    const resp: { id: string; html_url: string } = await res.json()
    const r = {
        created: res.status === 201,
        statusText: res.statusText,
        html_url: resp.html_url,
    }
    if (!r.created)
        logError(
            `pull request ${issue} comment creation failed, ${r.statusText}`
        )
    else logVerbose(`pull request ${issue} comment created at ${r.html_url}`)

    return r
}

async function githubCreatePullRequestReview(
    script: PromptScript,
    info: GithubConnectionInfo,
    token: string,
    annotation: Diagnostic
) {
    assert(token)
    const { apiUrl, repository, issue, sha } = info
    const fetch = await createFetch()
    const url = `${apiUrl}/repos/${repository}/pulls/${issue}/comments`
    logVerbose(url)
    const body = {
        body: appendGeneratedComment(script, info, annotation.message),
        commit_id: sha,
        path: annotation.filename,
        start_line: annotation.range?.[0]?.[0],
        line: annotation.range?.[1]?.[0],
        subject_type: "line",
    }
    logVerbose(JSON.stringify(body, null, 2))
    const res = await fetch(url, {
        method: "POST",
        headers: {
            Accept: "application/vnd.github+json",
            Authorization: `Bearer ${token}`,
            "X-GitHub-Api-Version": GITHUB_API_VERSION,
        },
        body: JSON.stringify(body),
    })
    const resp: { id: string; html_url: string } = await res.json()
    logVerbose(JSON.stringify(resp, null, 2))
    const r = {
        created: res.status === 201,
        statusText: res.statusText,
        html_url: resp.html_url,
    }
    if (!r.created)
        logError(`commit ${sha} comment creation failed, ${r.statusText}`)
    else logVerbose(`commit ${sha} comment created at ${r.html_url}`)
    return r
}

export async function githubCreatePullRequestReviews(
    script: PromptScript,
    info: GithubConnectionInfo,
    annotations: Diagnostic[]
): Promise<boolean> {
    if (!annotations?.length) return true
    const { issue, sha } = info
    if (!issue) {
        logError("missing pull request number")
        return false
    }
    if (!sha) {
        logError("missing commit sha")
        return false
    }
    const token = await host.readSecret(GITHUB_TOKEN)
    if (!token) {
        logError("missing github token")
        return false
    }

    // code annotations
    for (const annotation of annotations)
        await githubCreatePullRequestReview(script, info, token, annotation)
    return true
}
