// This file is auto-generated by scripts/build-llmdata.mjs
// Do not edit manually - your changes will be overwritten
// Generated on: 2025-06-27T15:31:03.637Z
// Source: models.dev

/**
 * LLM data sourced from models.dev
 * @type {import('./types').LLMData}
 */
const LLMDATA = {
  "$schema": "../../../docs/public/schemas/llmdata.json",
  "version": "1.0.0",
  "generated": "2025-06-27T15:31:03.637Z",
  "source": "models.dev",
  "lastUpdated": "2025-06-27T15:31:03.637Z",
  "providers": [
    {
      "id": "example-provider",
      "detail": "A sample provider for demonstration",
      "url": "https://example.com",
      "aliases": {
        "large": "example-model"
      },
      "models": {},
      "env": {
        "API_KEY": {
          "required": true,
          "secret": true
        }
      }
    }
  ],
  "models": [
    {
      "id": "example-model",
      "provider": "example-provider",
      "name": "Example Model",
      "description": "A sample model for demonstration",
      "capabilities": {
        "tools": true,
        "vision": false
      },
      "context_length": 32768,
      "pricing": {
        "price_per_million_input_tokens": 1,
        "price_per_million_output_tokens": 2
      }
    }
  ],
  "aliases": {
    "large": "example-provider:example-model"
  },
  "pricings": {
    "example-provider:example-model": {
      "price_per_million_input_tokens": 1,
      "price_per_million_output_tokens": 2
    }
  }
}

export default LLMDATA
export const { providers, models, aliases, pricings } = LLMDATA
