// Type definitions for llmdata.js
// This file is auto-generated by scripts/build-llmdata.mjs

export interface LLMProvider {
    id: string
    detail: string
    url?: string
    aliases?: Record<string, string>
    models?: Record<string, any>
    env?: Record<string, any>
}

export interface LLMModel {
    id: string
    provider?: string
    name: string
    description?: string
    capabilities?: Record<string, any>
    context_length?: number
    pricing?: {
        price_per_million_input_tokens?: number
        price_per_million_output_tokens?: number
        input_cache_token_rebate?: number
    }
}

export interface LLMData {
    $schema: string
    version: string
    generated: string
    source: string
    lastUpdated?: string
    providers: LLMProvider[]
    models: LLMModel[]
    aliases: Record<string, string>
    pricings: Record<string, any>
}

declare const LLMDATA: LLMData
export default LLMDATA
export const providers: LLMProvider[]
export const models: LLMModel[]
export const aliases: Record<string, string>
export const pricings: Record<string, any>
