// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import type {
  DefOptions,
  Fenced,
  FileOutputOptions,
  PromptArgs,
  PromptTemplateString,
  RunPromptResult,
  ShellOutput,
  WorkspaceFile,
  WriteTextOptions,
  ElementOrArray,
  Awaitable,
} from "@genaiscript/core";

/**
 * Global functions that can be imported for IDE support
 * These are stub implementations - the actual implementations are provided at runtime
 */

/**
 * Setup prompt title and other parameters.
 * Exactly one call should be present on top of .genai.mts file.
 * Note: This is a stub implementation for import support.
 * The actual implementation is provided at runtime during prompt execution.
 */
export function script(options: PromptArgs): void {
    // Runtime implementation will be provided during prompt execution
    throw new Error("script() can only be called within a GenAIScript prompt execution context")
}

/**
 * Append given string to the prompt. It automatically appends "\n".
 * `` $`foo` `` is the same as `text("foo")`.
 * Note: This is a stub implementation for import support.
 * The actual implementation is provided at runtime during prompt execution.
 */
export function $(
    strings: TemplateStringsArray,
    ...args: any[]
): PromptTemplateString {
    // Runtime implementation will be provided during prompt execution
    throw new Error("$() can only be called within a GenAIScript prompt execution context")
}

/**
 * Defines `name` to be the (often multi-line) string `body`.
 * Similar to `text(name + ":"); fence(body, language)`
 * Note: This is a stub implementation for import support.
 * The actual implementation is provided at runtime during prompt execution.
 */
export function def(
    name: string,
    body:
        | string
        | WorkspaceFile
        | WorkspaceFile[]
        | ShellOutput
        | Fenced
        | RunPromptResult,
    options?: DefOptions
): string {
    // Runtime implementation will be provided during prompt execution
    throw new Error("def() can only be called within a GenAIScript prompt execution context")
}

/**
 * Append given string to the prompt. It automatically appends "\n".
 * Typically best to use `` $`...` ``-templates instead.
 * Note: This is a stub implementation for import support.
 * The actual implementation is provided at runtime during prompt execution.
 */
export function writeText(body: Awaitable<string>, options?: WriteTextOptions): void {
    // Runtime implementation will be provided during prompt execution
    throw new Error("writeText() can only be called within a GenAIScript prompt execution context")
}

/**
 * Declares a file that is expected to be generated by the LLM
 * Note: This is a stub implementation for import support.
 * The actual implementation is provided at runtime during prompt execution.
 */
export function defFileOutput(
    pattern: ElementOrArray<string | WorkspaceFile>,
    description?: string,
    options?: FileOutputOptions
): void {
    // Runtime implementation will be provided during prompt execution
    throw new Error("defFileOutput() can only be called within a GenAIScript prompt execution context")
}