#!/usr/bin/env node

/**
 * Build script that fetches LLM data from models.dev and generates llmdata.js
 */

import { writeFile, readFile } from 'fs/promises'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = join(__dirname, '..')

const MODELS_DEV_API = 'https://models.dev/api/models'
const OUTPUT_PATH = join(rootDir, 'packages/core/src/llmdata.js')

/**
 * Fetches model data from models.dev API
 */
async function fetchModelsDevData() {
    try {
        console.log('Fetching data from models.dev...')
        const response = await fetch(MODELS_DEV_API)
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`)
        }
        
        const data = await response.json()
        console.log(`Successfully fetched ${data.models?.length || 0} models from models.dev`)
        return data
    } catch (error) {
        console.warn(`Failed to fetch from models.dev: ${error.message}`)
        console.log('Using fallback data structure...')
        
        // Fallback structure based on existing llms.json patterns
        return {
            models: [
                {
                    id: "example-model",
                    name: "Example Model",
                    provider: "example-provider",
                    description: "A sample model for demonstration",
                    capabilities: { tools: true, vision: false },
                    context_length: 32768,
                    pricing: {
                        price_per_million_input_tokens: 1.0,
                        price_per_million_output_tokens: 2.0
                    }
                }
            ],
            providers: [
                {
                    id: "example-provider",
                    name: "Example Provider",
                    description: "A sample provider for demonstration",
                    url: "https://example.com",
                    aliases: { large: "example-model" },
                    environment: {
                        API_KEY: { required: true, secret: true }
                    }
                }
            ],
            lastUpdated: new Date().toISOString(),
            error: error.message
        }
    }
}

/**
 * Transforms models.dev data to match GenAIScript format
 */
function transformModelsData(modelsDevData) {
    const { models = [], providers = [], lastUpdated } = modelsDevData
    
    // Transform providers to match GenAIScript format
    const transformedProviders = providers.map(provider => ({
        id: provider.id || provider.name?.toLowerCase().replace(/\s+/g, '_'),
        detail: provider.description || provider.name,
        url: provider.url || provider.website,
        aliases: provider.aliases || {},
        models: provider.models || {},
        env: provider.environment || {}
    }))
    
    // Transform models to match GenAIScript format
    const transformedModels = models.map(model => ({
        id: model.id || model.name,
        provider: model.provider,
        name: model.name || model.id,
        description: model.description,
        capabilities: model.capabilities || {},
        context_length: model.context_length,
        pricing: model.pricing
    }))
    
    return {
        $schema: "../../../docs/public/schemas/llmdata.json",
        version: "1.0.0",
        generated: new Date().toISOString(),
        source: "models.dev",
        lastUpdated,
        providers: transformedProviders,
        models: transformedModels,
        aliases: extractAliases(transformedProviders),
        pricings: extractPricings(transformedModels)
    }
}

/**
 * Extracts aliases from providers
 */
function extractAliases(providers) {
    const aliases = {}
    
    providers.forEach(provider => {
        if (provider.aliases) {
            Object.entries(provider.aliases).forEach(([alias, model]) => {
                aliases[alias] = `${provider.id}:${model}`
            })
        }
    })
    
    return aliases
}

/**
 * Extracts pricing information from models
 */
function extractPricings(models) {
    const pricings = {}
    
    models.forEach(model => {
        if (model.pricing) {
            const key = model.provider ? `${model.provider}:${model.id}` : model.id
            pricings[key] = model.pricing
        }
    })
    
    return pricings
}

/**
 * Generates the JavaScript module content
 */
function generateLLMDataModule(transformedData) {
    const jsonData = JSON.stringify(transformedData, null, 2)
    
    return `// This file is auto-generated by scripts/build-llmdata.mjs
// Do not edit manually - your changes will be overwritten
// Generated on: ${new Date().toISOString()}
// Source: models.dev

/**
 * LLM data sourced from models.dev
 * @type {import('./types').LLMData}
 */
const LLMDATA = ${jsonData}

export default LLMDATA
export const { providers, models, aliases, pricings } = LLMDATA
`
}

/**
 * Creates a TypeScript definition file
 */
function generateTypeDefinitions() {
    return `// Type definitions for llmdata.js
// This file is auto-generated by scripts/build-llmdata.mjs

export interface LLMProvider {
    id: string
    detail: string
    url?: string
    aliases?: Record<string, string>
    models?: Record<string, any>
    env?: Record<string, any>
}

export interface LLMModel {
    id: string
    provider?: string
    name: string
    description?: string
    capabilities?: Record<string, any>
    context_length?: number
    pricing?: {
        price_per_million_input_tokens?: number
        price_per_million_output_tokens?: number
        input_cache_token_rebate?: number
    }
}

export interface LLMData {
    $schema: string
    version: string
    generated: string
    source: string
    lastUpdated?: string
    providers: LLMProvider[]
    models: LLMModel[]
    aliases: Record<string, string>
    pricings: Record<string, any>
}

declare const LLMDATA: LLMData
export default LLMDATA
export const providers: LLMProvider[]
export const models: LLMModel[]
export const aliases: Record<string, string>
export const pricings: Record<string, any>
`
}

/**
 * Main build function
 */
async function buildLLMData() {
    try {
        console.log('Starting LLM data build process...')
        
        // Fetch data from models.dev
        const modelsDevData = await fetchModelsDevData()
        
        // Transform the data
        console.log('Transforming data...')
        const transformedData = transformModelsData(modelsDevData)
        
        // Generate the module content
        console.log('Generating JavaScript module...')
        const moduleContent = generateLLMDataModule(transformedData)
        
        // Write the JavaScript file
        await writeFile(OUTPUT_PATH, moduleContent, 'utf8')
        console.log(`✓ Generated ${OUTPUT_PATH}`)
        
        // Generate and write TypeScript definitions
        const typeDefsPath = OUTPUT_PATH.replace('.js', '.d.ts')
        const typeDefsContent = generateTypeDefinitions()
        await writeFile(typeDefsPath, typeDefsContent, 'utf8')
        console.log(`✓ Generated ${typeDefsPath}`)
        
        console.log('LLM data build completed successfully!')
        
        // Output summary
        console.log(`\nSummary:`)
        console.log(`- Providers: ${transformedData.providers.length}`)
        console.log(`- Models: ${transformedData.models.length}`)
        console.log(`- Aliases: ${Object.keys(transformedData.aliases).length}`)
        console.log(`- Pricing entries: ${Object.keys(transformedData.pricings).length}`)
        
    } catch (error) {
        console.error('Build failed:', error)
        process.exit(1)
    }
}

// Run the build if this script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
    buildLLMData()
}

export { buildLLMData }