name: genai commit tests

on:
    workflow_dispatch:
    push:
        branches: [dev]
        paths:
            - "packages/core/**"
            - "packages/sample/**"
            - "packages/cli/**"
concurrency:
    group: -genai-test-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions:
    models: read
    contents: read
    pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile:action
            - name: generate dummy result
              working-directory: packages/sample
              run: mkdir -p temp && touch temp/commit-tests.txt
            - name: select llm tests to run
              run: node packages/cli/built/genaiscript.cjs run test-commit --out-trace $GITHUB_STEP_SUMMARY -p github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: run llm tests
              working-directory: packages/sample
              run: xargs -r -a temp/commit-tests.txt node ../cli/built/genaiscript.cjs test --out-summary $GITHUB_STEP_SUMMARY --test-delay 10 -p github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
