name: genai docs
on:
    workflow_dispatch:
    pull_request:
        types: [review_requested]
        paths:
            - "packages/**/*.ts"
concurrency:
    group: docs-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    gen-docs:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
            models: read
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: git fetch dev
              run: git fetch origin && git pull origin dev:dev
            - name: /docs
              run: node packages/cli/built/genaiscript.cjs run docs "packages/**/*.ts" --out ./temp/genai/docs -prc -p github --out-trace $GITHUB_STEP_SUMMARY --vars diff=true --vars pretty=true --vars applyEdits=true --vars defaultBranch=dev
              env:
                  DEBUG: "script*"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.base.sha}}
            - name: typecheck
              run: yarn typecheck
            - name: git status
              run: git status
            - name: commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "genai: /docs [skip ci]"
                  file_pattern: packages/**/*.ts
            - name: archive
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: genai-results
                  path: ./temp/genai/**
