name: genai issue bot
on:
    issues:
        types: [closed]
concurrency:
    group: issue-bot-${{ github.event.issue.number }}
    cancel-in-progress: true
env:
    GENAISCRIPT_DEFAULT_REASONING_MODEL: ${{ vars.GENAISCRIPT_DEFAULT_REASONING_MODEL }}
    GENAISCRIPT_DEFAULT_REASONING_SMALL_MODEL: ${{ vars.GENAISCRIPT_DEFAULT_REASONING_SMALL_MODEL }}
    GENAISCRIPT_DEFAULT_MODEL: ${{ vars.GENAISCRIPT_DEFAULT_MODEL }}
    GENAISCRIPT_DEFAULT_SMALL_MODEL: ${{ vars.GENAISCRIPT_DEFAULT_SMALL_MODEL }}
    GENAISCRIPT_DEFAULT_VISION_MODEL: ${{ vars.GENAISCRIPT_DEFAULT_VISION_MODEL }}
jobs:
    reason:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            models: read
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: start ollama
              run: yarn ollama:start
            - name: genaiscript issue-review
              run: node packages/cli/built/genaiscript.cjs run issue-bot -prc bot --out-output $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_ISSUE: ${{ github.event.issue.number }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
