name: genai linters
on:
    workflow_dispatch:
    pull_request:
        types: [opened, ready_for_review, reopened]
        paths:
            - yarn.lock
            - "packages/core/**/*"
            - "packages/cli/**/*"
            - "packages/samples/**/*"
concurrency:
    group: linters-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
env:
    GENAISCRIPT_MODEL_LINTER: ${{ vars.GENAISCRIPT_MODEL_LINTER }}
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            models: read
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: git stuff
              run: git fetch origin && git pull origin dev:dev
            - name: genaiscript
              run: node packages/cli/built/genaiscript.cjs run linters --out ./temp/genai/linters -prr -m linter --out-trace $GITHUB_STEP_SUMMARY --vars defaultBranch=dev
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.base.sha}}
            - name: Archive genai results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: genai-results
                  path: ./temp/genai/**
